### ISSUE TITLE
minimum sleep time between 2 commands

### ISSUE THREAD

**Issue by fdelavra** [Erriez/milight_ibox2_control_python#14]
Hello and thanks for your development.
I have some problems with commands: if my sleep between 2 commands is too short (less than 0.1 sec), some command don't work, nothing just happen. 
Do you know what is the minimum sleep between 2 command to avoid command leak?
thanks

**Comment by Erriez** [comment]
@fdelavra Thanks 4 using this project. Correct, the iBox can miss commands when sending multiple commands after each other. Unfortunately, there is no guaranteed minimum delay between commands specified, so this is trial and error as you already discovered.
